on:
  workflow_call:
    inputs:
      build-config:
        type: string
      version:
        type: string
      package-version:
        type: string
      assembly-version:
        type: string
      file-version:
        type: string
      informational-version:
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - ${{ fromjson(inputs.build-config) }}
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo "$MATRIX"
      env:
        MATRIX: ${{ tojson(matrix) }}

    - run: echo ${{ inputs.version }}
    - run: echo ${{ inputs.package-version }}
    - run: echo ${{ inputs.assembly-version }}
    - run: echo ${{ inputs.file-version }}
    - run: echo ${{ inputs.informational-version }}

  # test:
  #   needs: build
  #   strategy:
  #     matrix:
  #       include:
  #       - ${{ fromjson(inputs.build-config) }}
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - run: echo "$MATRIX"
  #     env:
  #       MATRIX: ${{ tojson(matrix) }}
