on:
  workflow_call:
    inputs:
      channel:
        type: string
      environment:
        type: string

jobs:

  nuget_push:
    if: inputs.channel == 'nuget.org'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
    steps:
      - run: dotnet nuget push **/*.nupkg --k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
