on:
  push:
    branches:
      - main
  release:
    types:
      - published
  # 'pull_request_target' exposes repo secrets and repo write permissions to PR, so manual approval is enforced 
  # via 'external' environment. Jobs that require secrets should have an (indirect) dependency (needs) on the
  # 'authorize' job.
  pull_request_target:

name: pipeline
env:
  ref: ${{ github.event.pull_request.head.ref || github.ref }}
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  dotnet-version: |
    7.0.x
    6.0.x

jobs:
  echo-ref:
    runs-on: ubuntu-latest
    env:
      json: ${{ tojson(github) }}
    steps:
      - run: echo $json

  authorize:
    # Blog https://iterative.ai/blog/testing-external-contributions-using-github-actions-secrets
    environment:
      ${{ (github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository) &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ✓

  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.fullSemVer }}
      package-version: ${{ steps.gitversion.outputs.fullSemVer }}
      assembly-version: ${{ steps.gitversion.outputs.assemblySemVer }}
      file-version: ${{ steps.gitversion.outputs.assemblySemFileVer }}
      informational-version: ${{ steps.gitversion.outputs.informationalVersion }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          # v5.10.0 of GitVersion has a fix for incorrect versions when building tags. See https://github.com/GitTools/GitVersion/issues/2838
          # It appears that the fix then had a regression in a later version, so locking in 5.10.0.  See https://github.com/GitTools/GitVersion/issues/3351#issuecomment-1403657689
          versionSpec: '5.10.0' 

      - name: Determine version
        uses: gittools/actions/gitversion/execute@v0.10.2
        id: gitversion
        with:
          useConfigFile: true

  build:
    needs:
      - determine-version
      - authorize
    name: build (v${{ needs.determine-version.outputs.version }})
    runs-on: ubuntu-latest
    env:
      msbuild-version-args: /p:Version="${{ needs.determine-version.outputs.version }}" /p:PackageVersion="${{ needs.determine-version.outputs.package-version }}" /p:AssemblyVersion="${{ needs.determine-version.outputs.assembly-version }}" /p:FileVersion="${{ needs.determine-version.outputs.file-version }}" /p:InformationalVersion="${{ needs.determine-version.outputs.informational-version }}"
    outputs:
      dotnet-version: ${{ env.dotnet-version }}
      msbuild-version-args: ${{ env.msbuild-version-args }}
    steps:
      # Setup
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - run: dotnet --info

      # Checkout
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.ref }}
          fetch-depth: 1

      # Build
      - run: dotnet build -c Release ${{ env.msbuild-version-args }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            **/bin
            **/obj
          if-no-files-found: error
          retention-days: 7

  test:
    needs: build
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    uses: ./.github/workflows/test.yml
    with:
      build-config: ${{ tojson(matrix) }}
      pull-request: ${{ github.event_name == 'pull_request_target' && tojson(github.event.pull_request) || '' }}
      dotnet-version: ${{ needs.build.outputs.dotnet-version }}

  analysis:
    needs: build
    uses: ./.github/workflows/sonarcloud.yml
    with:
      pull-request: ${{ github.event_name == 'pull_request_target' && tojson(github.event.pull_request) || '' }}
      dotnet-version: ${{ needs.build.outputs.dotnet-version }}
    secrets: inherit

  pack:
    needs:
      - determine-version
      - build
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet-version }}

      # Checkout
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.ref }}
          fetch-depth: 1

      # Restore build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      # Pack
      - run: dotnet pack --no-build -c Release ${{ needs.build.outputs.msbuild-version-args }}
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ needs.determine-version.outputs.package-version }}
          path: |
            **/*.*nupkg
          if-no-files-found: error
          retention-days: 90

  deploy:
    needs:
      - determine-version
      - test
      - analysis
      - pack
    if: github.event_name == 'release'
    environment: production
    runs-on: ubuntu-latest
    steps:
      # Restore release artifacts
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: release-${{ needs.determine-version.outputs.package-version }}

      - name: push - nuget.org
        env:
          NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
