on:
  - push
  - pull_request

name: build and test
jobs:
  build-and-test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    uses: ./.github/workflows/build.yml
    with:
      build-config: ${{ tojson(matrix) }}
