on:
  workflow_call:
    inputs:
      build-config:
        type: string
      pull-request: 
        type: string
      dotnet-version:
        type: string

env:
  ref: ${{ inputs.pull-request != '' && fromjson(inputs.pull-request).head.sha || github.ref }}

jobs:
  test:
    strategy:
      matrix:
        include:
          - ${{ fromjson(inputs.build-config) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.ref }}
          fetch-depth: 1

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - run: dotnet --info
      - run: dotnet test -c Release
